version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app/src
    environment:
      FLASK_ENV: development
  test:
    build: .
    volumes:
      - .:/app
    working_dir: /app/src
    environment:
      FLASK_ENV: testing
      PYTHONPATH: /app/src
    command: pytest tests/ --disable-warnings